version: "3"
services:
  court-hearing-event-receiver:
    build:
      context: .
    network_mode: "host"
    container_name: court-hearing-event-receiver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  localstack-cher:
    image: localstack/localstack:latest
    networks:
      - hmpps
    container_name: localstack-cher
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=sns,sqs,s3
      - DEBUG=${DEBUG- }
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  hmpps:
