info.app:
  name: Court Hearing Event Receiver
  version: 1.0

spring:
  application:
    name: court-hearing-event-receiver
  codec:
    max-in-memory-size: 10MB

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  profiles:
    group:
      test:
        - "stdout"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${hmppsauth.baseurl}/issuer
          jwk-set-uri: ${hmppsauth.baseurl}/.well-known/jwks.json

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

included-court-codes: "B01BE,B01BH,B01CE,B01CN,B01DU,B01EF,B01FA,B01GQ,B01GU,B01IX,B01KR,B01LA,B01LY,B01MN,B01ND,B01NM,B01OK,B03AX,B03DE,B03OT,B04BP,B04BQ,B04CO,B04HQ,B04KO,B05BK,B05BW,B05PK,B06AN,B06BV,B06IS,B06MK,B06OJ,B07DM,B07ED,B07FQ,B10BD,B10BF,B10FR,B10JJ,B10JQ,B10LX,B10MR,B11EI,B11JP,B11KF,B12GH,B12LK,B12LT,B12PA,B13CC,B13HD,B13HT,B14AV,B14ET,B14LO,B16BG,B16CJ,B16GB,B16HE,B17JA,B20BL,B20EB,B20EY,B20NQ,B20OQ,B21DA,B21JI,B22GR,B22HM,B22KS,B22MZ,B22OS,B23HS,B23HS,B23PP,B30PG,B30PI,B31IT,B31JV,B32HX,B32UD,B33HU,B33II,B34JS,B34NX,B35CZ,B35HF,B35KE,B36FZ,B36HN,B36JU,B37HI,B40IM,B41ME,B41MJ,B41US,B42AZ,B42CM,B42CO,B42MB,B43JC,B43KB,B43KQ,B43LV,B43OX,B44AG,B44BA,B44JK,B44KM,B44MA,B45GC,B45MH,B46DB,B46DH,B46FO,B46IR,B46IU,B46LN,B47CL,B47EC,B47GL,B47HB,B47OV,B50AW,B50BY,B50FI,B50JO,B50KH,B50NL,B52BB,B52CM,B52MY,B52OC,B52OZ,B53DJ,B54MW,B54WV,B55KL,B55OE,B60ID,B60JE,B60OW,B60WU,B61EH,B61NP,B62DC,B62IZ,B62KL,B62MV,B63AD,B63GN,B63IC,B63IE,B63NZ"
