version: 2.1

orbs:

  hmpps: ministryofjustice/hmpps@10
  jira: circleci/jira@1.2.2
  slack: circleci/slack@4.4.2

executors:
  builder:
    docker:
      - image: cimg/openjdk:16.0.2-browsers
    working_directory: ~/app

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run: ./gradlew build
      - run:
          name: Record the Application Version
          command: |
            $JAVA_HOME/bin/jar xvf build/libs/court-hearing-event-*.jar META-INF/build-info.properties
            APP_VERSION=$(grep 'build.version=' META-INF/build-info.properties | awk -F= '{print $2}')
            rm META-INF/build-info.properties
            # make up a good version name
            SHORT_HASH=$(git rev-parse --short HEAD)
            TAG=${APP_VERSION}.${SHORT_HASH}
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then
              TAG=${APP_VERSION}
            fi
            echo $TAG > ./app_version.txt
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts
            - app_version.txt
      - slack/notify:
          event: fail
          template: basic_fail_1

  test-integration:
    executor:
      name: hmpps/localstack
      jdk_tag: "19.0"
      localstack_tag: "3.0"
      services: "s3,sqs,sns"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - run:
          name: Set up AWS
          command: bash src/test/resources/localstack/setup-aws.sh
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          environment:
            AWS_PROVIDER: localstack
            SPRING_PROFILES_ACTIVE: test
          command: ./gradlew integrationTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - helm_lint
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          helm_additional_args: --values ./court-hearing-event-receiver/values-live.yaml
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
            - helm_lint
            - test-integration
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          helm_additional_args: --values ./court-hearing-event-receiver/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          helm_additional_args: --values ./court-hearing-event-receiver/values-live.yaml
          slack_channel_name: probation_in_court_dev
          slack_notification: true
          context:
            - hmpps-common-vars
            - court-probation-live-prod
          requires:
            - request-prod-approval
      - test-integration:
          name: test-integration

  security:
    triggers:
      - schedule:
          cron: "47 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "23 4 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
