version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.11.11
  jira: circleci/jira@1.2.2
  slack: circleci/slack@4.4.2

executors:
  builder:
    docker:
      - image: circleci/openjdk:16-jdk-buster-browsers
    working_directory: ~/app

  validator-integration:
    docker:
      - image: circleci/openjdk:16-jdk-buster-browsers
      - image: localstack/localstack:latest
        environment:
          - SERVICES=sqs,sns,s3
          - DEBUG=${DEBUG- }
          - DATA_DIR=/tmp/localstack/data
          - DOCKER_HOST=unix:///var/run/docker.sock
          - AWS_EXECUTION_ENV=True
          - DEFAULT_REGION=eu-west-2
          - TMPDIR=/private
    environment:
      _JAVA_OPTIONS: -Xmx256m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false
    working_directory: ~/app

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run: ./gradlew build
      - run:
          name: Record the Application Version
          command: |
            jar xvf build/libs/court-hearing-event-*.jar BOOT-INF/classes/META-INF/build-info.properties
            APP_VERSION=$(grep 'build.version=' BOOT-INF/classes/META-INF/build-info.properties | awk -F= '{print $2}')
            rm BOOT-INF/classes/META-INF/build-info.properties
            # make up a good version name
            SHORT_HASH=$(git rev-parse --short HEAD)
            TAG=${APP_VERSION}.${SHORT_HASH}
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then
              TAG=${APP_VERSION}
            fi
            echo $TAG > ./app_version.txt
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts
            - app_version.txt
      - slack/notify:
          event: fail
          template: basic_fail_1

  test-integration:
    executor: validator-integration
    steps:
      - checkout
      - hmpps/install_aws_cli
      - run:
          name: Wait for SQS to be ready
          command: curl -4 --connect-timeout 30 --retry-connrefused --retry 20 --retry-delay 5 http://localhost:4566
      - run:
          name: Set up S3
          command: bash src/test/resources/localstack/setup-sns.sh
      - run:
          name: Set up queues
          command: bash src/test/resources/localstack/setup-sns.sh
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          environment:
            AWS_PROVIDER: localstack
            SPRING_PROFILES_ACTIVE: test
          command: ./gradlew integrationTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
                - helm_lint
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - build
            - build_docker
            - helm_lint
            - test-integration
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - court-probation-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_channel_name: probation_in_court_dev
          slack_notification: true
          context:
            - hmpps-common-vars
            - court-probation-prod
          requires:
            - request-prod-approval
      - test-integration:
          name: test-integration

  security:
    triggers:
      - schedule:
          cron: "47 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "23 4 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars


