---
generic-service:
  nameOverride: court-hearing-event-receiver

  serviceAccountName: "court-case-service"

  image:
    repository: quay.io/hmpps/court-hearing-event-receiver
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    v0_47_enabled: false
    v1_2_enabled: true
    enabled: true
    modsecurity_enabled: false
    hosts:
      - app-hostname.local    # override per environment
    path: /

  autoscaling:
    enabled: true
    targetCPUUtilizationPercentage: 100

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    AWS_REGION_NAME: "eu-west-2"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    court-hearing-event-receiver:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    court-case-events-topic:
      aws_sns_topic_arn: topic_arn
    crime-portal-gateway-s3-credentials:
      aws_s3_bucket_name: bucket_name

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    global-protect: "35.176.93.186/32"

generic-prometheus-alerts:
  targetApplication: court-hearing-event-receiver
  alertSeverity: slack-hmpps-user-preferences
