---
generic-service:
  ingress:
    host: court-hearing-event-receiver-dev.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-dev-cert-secret
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 100

env:
  HMPPS_AUTH_BASE_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
