---
generic-service:
  ingress:
    host: court-hearing-event-receiver-dev.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-dev-cert-secret

  autoscaling:
    minReplicas: 2
    maxReplicas: 3

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 250m
      memory: 350Mi

  env:
    HMPPSAUTH_BASEURL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    FEATURE_USE_INCLUDED_COURTS_LIST: false
