---
generic-service:
  ingress:
    host: court-hearing-event-receiver.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret

  autoscaling:
    minReplicas: 2
    maxReplicas: 4

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 500m
      memory: 700Mi

  env:
    HMPPSAUTH_BASEURL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

  allowlist:
    hmcts-1: "51.140.24.220/32" # this may be redundant - TBD after successful receipt of payload
    hmcts-2: "51.140.52.246/32" # we understand this is the externally facing IP we should receive traffic from
