---
generic-service:
  ingress:
    host: court-hearing-event-receiver-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-preprod-cert-secret
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 100

env:
  HMPPS_AUTH_BASE_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
