---
generic-service:
  ingress:
    hosts:
      - court-hearing-event-receiver-preprod.hmpps.service.justice.gov.uk

  autoscaling:
    minReplicas: 2
    maxReplicas: 4

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 500m
      memory: 700Mi

  env:
    HMPPSAUTH_BASEURL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    FEATURE_USE_INCLUDED_COURTS_LIST: false

  allowlist:
    hmcts-1: "51.140.138.86/32"
    hmcts-2: "51.145.115.21/32"
    hmcts-3: "51.143.153.50/32"
