---
generic-service:
  ingress:
    host: court-hearing-event-receiver.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 100
  resources:
    cpu:
      limit: 5000m
      request: 500m
    memory:
      limit: 1200Mi
      request: 700Mi
