---
generic-service:
  ingress:
    host: court-hearing-event-receiver-dev.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-dev-cert-secret
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 100
  resources:
    cpu:
      limit: 5000m
      request: 250m
    memory:
      limit: 1200Mi
      request: 350Mi
